cask_args appdir: '/Applications'

brew 'ag'
brew 'bash'
brew 'bat'
brew 'btop'
brew 'curl'
brew 'duf'
brew 'dust'
brew 'eza'
brew 'fastfetch'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'git-lfs'
brew 'gnu-sed'
brew 'gping'
brew 'jq'
brew 'lazygit'
brew 'make'
brew 'neovim'
brew 'ollama'
brew 'openssh'
brew 'openssl'
brew 'procs'
brew 'ripgrep'
brew 'sd'
brew 'tlrc'
brew 'tmux'
brew 'vivid'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-fast-syntax-highlighting'

cask 'claude'
cask 'discord'
cask 'docker'
cask 'font-fira-code-nerd-font'
cask 'ghostty'
cask 'keka'
cask 'nikitabobko/tap/aerospace'
cask 'obsidian'
cask 'raycast'
cask 'spotify'
cask 'whatsapp'

# ------------------------------------------------------------------------------
# Added by Claude (2026-09-14): installed on this Mac but missing above.
# Review and delete anything you don't want on the new Mac.
# ------------------------------------------------------------------------------

tap 'gromgit/fuse'

brew 'codeburn'
brew 'gh'
brew 'gromgit/fuse/ntfs-3g-mac'
brew 'poppler'
brew 'python@3.11'
brew 'starship'
brew 'tree'
brew 'tree-sitter-cli'
brew 'xh'

cask 'db-browser-for-sqlite'
cask 'dockdoor'
cask 'font-meslo-lg-nerd-font'
cask 'free-download-manager'
cask 'iina'
cask 'logitech-g-hub'
cask 'macfuse'
cask 'mounty'
cask 'obs'
cask 'visual-studio-code'
cask 'vorssaint'
cask 'zen'
cask 'zotero'

